name: note_app_provider
description: A simple notes app using Provider state management.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.1.1

flutter:
  uses-material-design: true
